imprime_tech_use_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:index" }
    methods:  GET

imprime_tech_use_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:new" }
    methods:  [GET, POST]

imprime_tech_use_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:edit" }
    methods:  [GET, POST]

imprime_tech_use_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:update" }
    methods:  [POST, PUT]

imprime_tech_use_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:delete" }
    methods:  [GET, DELETE]

imprime_tech_use_reset:
    path:     /{id}/reset
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:reset" }
    methods:  [GET, PUT]

imprime_tech_use_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:deleteGroup" }
    methods:  POST

imprime_tech_use_search:
    path:     /search
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:search" }
    methods:  [GET, POST]

imprime_tech_use_show_numero_it_ajax:
    path:     /show-numero-it-ajax
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:showNumeroITAjax" }
    methods:  POST

imprimes_tech_generate_used_ajax:
    path:     /generate-feuille-it-ajax
    defaults: { _controller: "AdminBundle:CtImprimeTechUse:generateFeuilleUsedIT" }
    methods:  [GET, POST]
    